#! /bin/bash

sed -n '/\[tool.poetry.dependencies\]/, /^$/{ /^\w/ p }' pyproject.toml | \
sed -e 's/ =.*/@latest/' | grep -v python | xargs poetry add

sed -n '/\[tool.poetry.group.dev.dependencies\]/, /^$/{ /^\w/ p }' pyproject.toml | \
sed -e 's/ =.*/@latest/' | grep -v python | xargs poetry add --group dev

poetry update
poetry export --with dev --without-hashes --format requirements.txt --output requirements.txt

pre-commit autoupdate


sed -i "1s/^/# THIS FILE IS AUTOGENERATED. SEE README FOR HOW TO CHANGE\n/" requirements.txt
